import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primarySky: "#C3EBFA",
        secondarySkyLight: "#EDF9FD",
        tertiaryPurple: "#CFCEFF",
        PurpleLight: "#FAE27C",
        YellowLight: "#FEFCE8",
        purple: "#CBACF9",
        text: "#1f2937",
        p4: "#eaedff",
        s3: "#00b5ef",
        s4: "#ff53cb",
        s5: "#6c84ff",
        s6: "#443da1",
        s7: "#ff53cb",
        primaryLight: "#0252CD",
        primaryDark: "#428DFF",
        secondary: "#FFBE62",
        challengeRed: "#E15A46",
        learningsGreen: "#02BC7D",
        cross: "#424B5C",
        crossDark: "#F6F7F9",
        white500: "#6F74A7",
        white800: "#f2f2f2",
        white900: "#FFFFFF",
        black200: "#191e24",
        black300: "#1d232a",
        black400: "#778295",
        graphicOffWhite: "#F9FBFC",
        graphicOffWhite2: "#E5F1FF",
        graphicOffWhite3: "#F7F7F7",
        graphicTurquoise: "#1AE5FF",
        graphicLighterBlue: "#A9CCEA",
        graphicPaleBlue: "#289DF2",
        graphicLightBlue: "#2889DB",
        graphicMidBlue: "#287DD1",
        graphicDarkBlue: "#284D89",
        graphicDarkerBlue: "#28385E",
        graphicDarkestBlue: "#282E5C",
        graphicGrey: "#0F3775",
        graphicDarkGrey: "#0F3157",
        graphicPaleRed: "#FF5C66",
        graphicLightRed: "#FF4D6B",
      },
    },
  },
  plugins: [],
};
export default config;
